part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: const Color(0x33000000),
  background: const Color(0xFFFFFFFF),
  foreground: const Color(0xFF0A0A0A),
  primary: const Color(0xFF1447E6),
  primaryForeground: const Color(0xFFEFF6FF),
  secondary: const Color(0xFFF5F5F5),
  secondaryForeground: const Color(0xFF171717),
  muted: const Color(0xFFF5F5F5),
  mutedForeground: const Color(0xFF737373),
  destructive: const Color(0xFFE7000B),
  destructiveForeground: const Color(0xFFFAFAFA),
  error: const Color(0xFFE7000B),
  errorForeground: const Color(0xFFFAFAFA),
  card: const Color(0xFFFFFFFF),
  border: const Color(0xFFE5E5E5),
  extensions: const [AppColors()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: const Color(0x7A000000),
  background: const Color(0xFF0A0A0A),
  foreground: const Color(0xFFFAFAFA),
  primary: const Color(0xFF193CB8),
  primaryForeground: const Color(0xFFEFF6FF),
  secondary: const Color(0xFF262626),
  secondaryForeground: const Color(0xFFFAFAFA),
  muted: const Color(0xFF262626),
  mutedForeground: const Color(0xFFA1A1A1),
  destructive: const Color(0xFFFF6467),
  destructiveForeground: const Color(0xFFFAFAFA),
  error: const Color(0xFFFF6467),
  errorForeground: const Color(0xFFFAFAFA),
  card: const Color(0xFF171717),
  border: const Color(0x1AFFFFFF),
  extensions: const [AppColors()],
);

/// Provides convenient access to theme extensions on [FColors].
///
/// ```dart
/// final accent = context.theme.colors.app.accent; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final accent = context.theme.colors.accent; ✅
///
/// final accent = context.theme.colors.extension<AppColors>().accent; ❌
/// ```
extension FColorsExtensions on FColors {
  AppColors get app => extension<AppColors>();
}

/// Custom color tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and
/// [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.

@immutable
class AppColors extends ThemeExtension<AppColors> {
  // final Color accent;

  const AppColors();

  @override
  AppColors copyWith() => const AppColors();

  @override
  AppColors lerp(covariant AppColors? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppColors();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppColors && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
