part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Icon tokens for the generated theme.
FIcons _icons() => const FIcons(
  arrowLeft: FIcon(FLucideIcons.arrowLeft),
  calendar: FIcon(FLucideIcons.calendar),
  check: FIcon(FLucideIcons.check),
  chevronDown: FIcon(FLucideIcons.chevronDown),
  chevronLeft: FIcon(FLucideIcons.chevronLeft),
  chevronRight: FIcon(FLucideIcons.chevronRight),
  chevronUp: FIcon(FLucideIcons.chevronUp),
  chevronsUpDown: FIcon(FLucideIcons.chevronsUpDown),
  circleAlert: FIcon(FLucideIcons.circleAlert),
  clock4: FIcon(FLucideIcons.clock4),
  ellipsis: FIcon(FLucideIcons.ellipsis),
  error: FIcon(FLucideIcons.circleAlert),
  eye: FIcon(FLucideIcons.eye),
  eyeClosed: FIcon(FLucideIcons.eyeClosed),
  gripHorizontal: FIcon(FLucideIcons.gripHorizontal),
  gripVertical: FIcon(FLucideIcons.gripVertical),
  loader: FIcon(FLucideIcons.loader),
  loaderCircle: FIcon(FLucideIcons.loaderCircle),
  loaderPinwheel: FIcon(FLucideIcons.loaderPinwheel),
  search: FIcon(FLucideIcons.search),
  userRound: FIcon(FLucideIcons.userRound),
  x: FIcon(FLucideIcons.x),
);
