part of 'theme.dart';

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({
  required FColors colors,
  required FTypography typography,
  required bool touch,
}) {
  const borderRadius = FBorderRadius();
  return FStyle(
    formFieldStyle: .inherit(
      colors: colors,
      typography: typography,
      touch: touch,
    ),
    focusedOutlineStyle: FFocusedOutlineStyle(
      color: colors.primary,
      borderRadius: borderRadius.md,
    ),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(
      color: colors.foreground,
      size: typography.body.lg.fontSize,
    ),
    tappableStyle: FTappableStyle(),
    extensions: const [AppStyle()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final cardRadius = context.theme.style.app.cardRadius; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final cardRadius = context.theme.style.cardRadius; ✅
///
/// final cardRadius = context.theme.style.extension<AppStyle>().cardRadius; ❌
/// ```
extension FStyleExtensions on FStyle {
  AppStyle get app => extension<AppStyle>();
}

/// Custom style tokens unique to your app.
///
/// Add your fields below, then implement [copyWith], [lerp], [==], and
/// [hashCode].
/// See https://api.flutter.dev/flutter/material/ThemeExtension-class.html.

@immutable
class AppStyle extends ThemeExtension<AppStyle> {
  // final double cardRadius;

  const AppStyle();

  @override
  AppStyle copyWith() => const AppStyle();

  @override
  AppStyle lerp(covariant AppStyle? other, double t) {
    if (other == null) {
      return this;
    }
    return const AppStyle();
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppStyle && runtimeType == other.runtimeType;

  @override
  int get hashCode => runtimeType.hashCode;
}
